const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
let state={bank:null,name:'',length:50,mode:'test',questions:[],index:0,score:0,answered:0,manualCorrect:0,selected:false};
const banks={CRP1:()=>window.CRP1_DATA,CRP2:()=>window.CRP2_DATA};
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function openSetup(name){state.name=name;state.bank=banks[name]();$('#setupTitle').textContent=name;$('#setupDescription').textContent=name==='CRP1'?`${state.bank.length} questions from the uploaded CRP1 PDF. The source does not contain marked answers, so Test mode uses self-marking.`:`${state.bank.length} questions from the uploaded CRP2 PDF. Marked answers in the source are used for automatic scoring.`;$('#lengthOptions button').forEach(b=>b.classList.toggle('selected',b.dataset.length==='50'));state.length=50;state.mode='test';$$('.mode').forEach(b=>b.classList.toggle('selected',b.dataset.mode==='test'));show('setup')}
$$('[data-start]').forEach(b=>b.onclick=()=>openSetup(b.dataset.start));$('#homeBtn').onclick=()=>show('home');$('#setupBack').onclick=()=>show('home');$('#historyBtn').onclick=()=>{renderHistory();show('history')};$('#historyBack').onclick=()=>show('home');
$('#lengthOptions').onclick=e=>{if(e.target.dataset.length){state.length=e.target.dataset.length;$$('#lengthOptions button').forEach(b=>b.classList.toggle('selected',b===e.target))}};
$$('.mode').forEach(b=>b.onclick=()=>{$$('.mode').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.mode=b.dataset.mode});
$('#beginBtn').onclick=startQuiz;
function startQuiz(){let pool=shuffle(state.bank);if(state.length!=='all')pool=pool.slice(0,Math.min(Number(state.length),pool.length));state.questions=pool.map(q=>({...q,choices:shuffle(q.choices)}));state.index=0;state.score=0;state.answered=0;state.manualCorrect=0;show('quiz');renderQuestion()}
function renderQuestion(){const q=state.questions[state.index];state.selected=false;$('#quizName').textContent=state.name;$('#quizCounter').textContent=`Question ${state.index+1} of ${state.questions.length}`;$('#sourceNum').textContent=`Source #${q.id}`;$('#modeLabel').textContent=state.mode.toUpperCase();$('#scorePill').textContent=`${state.score} correct`;$('#progressBar').style.width=`${((state.index)/state.questions.length)*100}%`;$('#questionText').textContent=q.question;$('#feedback').className='feedback';$('#feedback').textContent='';$('#nextBtn').disabled=true;$('#nextBtn').textContent=state.index===state.questions.length-1?'Finish →':'Next →';const wrap=$('#choices');wrap.innerHTML='';q.choices.forEach((c,i)=>{const btn=document.createElement('button');btn.className='choice';btn.innerHTML=`<span class="letter">${String.fromCharCode(65+i)}</span><span>${escapeHtml(c.text)}</span>`;btn.onclick=()=>choose(i,btn,c);wrap.appendChild(btn)})}
function choose(i,btn,c){if(state.selected)return;state.selected=true;state.answered++;$$('.choice').forEach(x=>x.disabled=true);btn.classList.add('selected');const q=state.questions[state.index];const keyed=q.choices.findIndex(x=>x.correct);if(state.name==='CRP2'&&keyed>=0){if(c.correct){state.score++;btn.classList.add('correct');setFeedback('Correct!','ok')}else{btn.classList.add('wrong');$$('.choice')[keyed].classList.add('correct');setFeedback(`Incorrect. Correct answer: ${String.fromCharCode(65+keyed)}. ${q.choices[keyed].text}`,'bad')}}else{setFeedback('CRP1 has no answer key in the uploaded PDF. Mark your answer below.','') ;addManualButtons()}$('#scorePill').textContent=`${state.score} correct`;$('#nextBtn').disabled=false}
function addManualButtons(){const f=$('#feedback');f.innerHTML=`${escapeHtml(f.textContent)} <span class="manual"><button class="secondary" onclick="manual(true)">I got it right</button> <button class="danger" onclick="manual(false)">I got it wrong</button></span>`;}
window.manual=ok=>{if(ok){state.score++;$('#scorePill').textContent=`${state.score} correct`;setFeedback('Marked correct.','ok')}else setFeedback('Marked incorrect.','bad');$$('.manual button').forEach(b=>b.disabled=true)};
function setFeedback(t,cls){const f=$('#feedback');f.textContent=t;f.className='feedback '+cls;if(state.name==='CRP1'&&state.selected) addManualButtons();}
$('#nextBtn').onclick=()=>{if(state.index<state.questions.length-1){state.index++;renderQuestion()}else finishQuiz()};$('#skipBtn').onclick=()=>{if(!state.selected){state.answered++;state.index<state.questions.length-1?(state.index++,renderQuestion()):finishQuiz()}};
$('#quitBtn').onclick=()=>{if(confirm('Quit this test? The attempt will be recorded as incomplete.'))finishQuiz(true)};
function finishQuiz(incomplete=false){const total=state.questions.length;const pct=total?Math.round(state.score/total*100):0;const rec={name:state.name,score:state.score,total,pct,incomplete,date:new Date().toISOString(),mode:state.mode};const h=JSON.parse(localStorage.getItem('crpHistory')||'[]');h.unshift(rec);localStorage.setItem('crpHistory',JSON.stringify(h.slice(0,100)));$('#resultTitle').textContent=incomplete?'Attempt Saved':'Excellent work!';$('#resultScore').textContent=`${state.score}/${total}`;$('#resultDetails').textContent=`${pct}% • ${state.name} • ${state.mode==='test'?'Test':'Study'}${incomplete?' • Incomplete':''}`;show('result')}
$('#retryBtn').onclick=()=>openSetup(state.name);$('#resultHomeBtn').onclick=()=>show('home');
function renderHistory(){const h=JSON.parse(localStorage.getItem('crpHistory')||'[]');const el=$('#historyList');if(!h.length){el.innerHTML='<div class="empty">No attempts yet. Start CRP1 or CRP2 to build your history.</div>';return}el.innerHTML=h.map((x,i)=>`<div class="history-item"><div><strong>${x.name} ${x.incomplete?'• Incomplete':''}</strong><small>${new Date(x.date).toLocaleString()} • ${x.mode}</small></div><div class="history-score">${x.score}/${x.total}<small> ${x.pct}%</small></div></div>`).join('')}
$('#clearHistory').onclick=()=>{if(confirm('Clear all saved history?')){localStorage.removeItem('crpHistory');renderHistory()}};
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
